[package]
name = "eyros"
version = "1.0.0"

[dependencies]
failure = "0.1.3"
num-traits = "0.2.6"
#random-access-storage = "1.0.0"
random-access-storage = { path = "../random-access-storage" }

[dev-dependencies]
rand = "0.6.1"
#random-access-disk = "0.7.0"
random-access-disk = { path = "../random-access-disk" }

[lib]
crate-type = [
    "cdylib",
    "lib",
]
