[package]
name = "eyros"
version = "1.0.0"
description = "multi-dimensional interval database"
license = "Parity-6.0.0 AND Apache-2.0"
readme = "readme.md"
repository = "https://github.com/peermaps/eyros"
homepage = "https://github.com/peermaps/eyros"
documentation = "https://docs.rs/eyros"
keywords = [ "database", "multi-dimensional", "interval", "time-series", "geospatial" ]
categories = [ "database" ]
edition = "2018"

[dependencies]
bincode = "1.0.1"
failure = "0.1.5"
lru = "0.1.13"
num-traits = "0.2.6"
random-access-disk = "1.0.0"
random-access-storage = "3.0.0"
serde = "1.0.82"

[dev-dependencies]
rand = "0.6.1"
random = "0.12.2"
tempfile = "3.0.7"
