[package]
name = "eyros"
version = "1.0.0"

[dependencies]
bincode = "1.0.1"
failure = "0.1.3"
num-traits = "0.2.6"
random-access-storage = "2.0.0"
serde = "1.0.82"

[dev-dependencies]
rand = "0.6.1"
random-access-disk = "0.8.0"

[lib]
crate-type = [
    "cdylib",
    "lib",
]
